[font]
size = 13
normal = {family="FiraCode Nerd Font", style="Regular"}

[window]
decorations = "none"
option_as_alt = 'Both'

[window.padding]
x = 7
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
